/**
 * DISTRACTOR ANALYZER
 * Reads the per-question distractorFeedbackMap generated by questionGenerator.js
 * and returns the correct educational feedback for the wrong block the student picked.
 */

/**
 * Analyze distractor errors and return educational feedback.
 * @param {Array}  wrongBlocks - [{ position, code }]
 * @param {Object} level       - current generated question (has distractorFeedbackMap)
 * @returns {Object} feedback object with explanation, reasoning, keyPoint, hint
 */
const analyzeDistractorError = (wrongBlocks, level) => {
  const firstCode = wrongBlocks[0]?.code;

  // 1. Look up the specific feedback generated for this distractor
  if (level.distractorFeedbackMap && firstCode && level.distractorFeedbackMap[firstCode]) {
    const fb = level.distractorFeedbackMap[firstCode];
    return {
      explanation: fb.explanation,
      reasoning:   fb.reasoning,
      keyPoint:    fb.keyPoint,
      hint:        fb.hint,
      // Pass through extra fields for AssemblyArea to render
      analogy:     fb.analogy,
      errorType:   fb.type,
    };
  }

  // 2. Fallback: derive feedback from the operation type
  return generateFallbackFeedback(level.operation);
};

/**
 * Fallback feedback when no specific map entry exists.
 */
const generateFallbackFeedback = (operation) => {
  const reasoningMap = {
    insertAtHead:     'Head insertion: create node → newNode.next = head → head = newNode. Order matters!',
    insertAtTail:     'Tail insertion: traverse to last → create node → lastNode.next = newNode → newNode.next = NULL.',
    removeAtHead:     'Head removal: temp = head → head = head.next → free temp. Save before you discard!',
    removeAtTail:     'Tail removal: traverse to second-last → temp = node.next → node.next = NULL → free temp.',
    insertAtPosition: 'Position insertion: traverse to predecessor → save its .next → link newNode → update predecessor.',
    removeAtPosition: 'Position removal: traverse to predecessor → save target in temp → bypass it → free temp.',
  };

  return {
    explanation: `This code block does not belong in a ${operation} operation.`,
    reasoning:   reasoningMap[operation] ?? 'Each step must logically contribute to the operation goal.',
    keyPoint:    'Compare the block with what each step of the operation is supposed to achieve.',
    hint:        'Ask yourself: does this line help create, connect, or clean up in the right order?',
  };
};

export { analyzeDistractorError };
