"""mistakes_json_columns

Revision ID: 7a03087b4d4f
Revises: b1aa961dfa6e
Create Date: 2026-05-25 23:23:14.543608

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7a03087b4d4f'
down_revision: Union[str, None] = 'b1aa961dfa6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE mistakes ALTER COLUMN your_answer TYPE JSON USING your_answer::json")
    op.execute("ALTER TABLE mistakes ALTER COLUMN correct_answer TYPE JSON USING correct_answer::json")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mistakes', 'correct_answer',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('mistakes', 'your_answer',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
