"""add_concept_mastery

Revision ID: fa6e3faadff0
Revises: c5d6e7f8a9b0
Create Date: 2026-06-08 13:42:51.731465

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fa6e3faadff0'
down_revision: Union[str, None] = 'c5d6e7f8a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_mastery',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept', name='uq_concept_mastery_user_concept')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concept_mastery')
    # ### end Alembic commands ###
